name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Init Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Login Finished"

    - name: Build Docker Image
      run: |
        docker build -t asaumet230/docker-graphql:0.0.1 .
        docker build -t asaumet230/docker-graphql:latest .
        
    - name: Push Docker Image
      run: |
        docker push asaumet230/docker-graphql:0.0.1
        docker push asaumet230/docker-graphql:latest
      
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
